### ISSUE TITLE
wiki/organisation updates: Stanford Data Science Initiative project, BORG project

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#18]
Hi all,

I'm working on getting the Pangloss project documentation in order, in preparation for some new work on fitting the mass model to weak lensing data. This project has some funding from Stanford, but it would be great to continue collaborating with you all. 

There's a few things that need doing!

* [x] @rhw could you check over the [new wiki pages](https://github.com/drphilmarshall/Pangloss/wiki/Inferring-the-Mass-Map-of-the-Observable-Universe-from-10-Billion-Galaxies) I made, please? The opening paragraph summary is something we could send to the SDSI people as they keep track of the projects they are supporting. #22 
* [x] @tcollett would you mind also reading through the new pages, and add comments and questions? This is probably best done on a separate issue thread, here: #19.
* [x] @charlottenosam It would be great to provide some simple notes on your BORG work on the Pangloss wiki, so that people at least know what to read (and then cite). I've given you push access to this base repo so you can add to the wiki. Here's the issue thread for discussion: #20 
* [x] Another issue thread: merging back in the code used in the BORG project? Discussion at #21
* [x] If anyone has future plans for the Pangloss code, please do add them to the [wiki home page](https://github.com/drphilmarshall/Pangloss/wiki), so we can try and keep track of things! We'll use the wiki to log progress on the weak lensing stuff.

Thanks!

Phil
